services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: moeda
      POSTGRES_PASSWORD: moeda
      POSTGRES_DB: moeda
    ports:
      - "5432:5432"
    volumes:
      - moeda_pg_data:/var/lib/postgresql/data

volumes:
  moeda_pg_data: {}
